// app/layout.tsx (serveur)
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Providers } from './providers';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200'],
});

export const metadata: Metadata = {
  title: 'Side Nav w/ Sub Menu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-white ${poppins.className} flex flex-col min-h-screen`}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
